const GET_CINEMAS_REQUEST = "GET_CINEMAS_REQUEST";
const GET_CINEMAS_SUCCESS = "GET_CINEMAS_SUCCESS";
const GET_CINEMAS_FAILURE = "GET_CINEMAS_FAILURE";
const GET_CINEMAS_SUCCESS_DATE = "GET_CINEMAS_SUCCESS_DATE";

export {
    GET_CINEMAS_REQUEST,
    GET_CINEMAS_FAILURE,
    GET_CINEMAS_SUCCESS,
    GET_CINEMAS_SUCCESS_DATE
}